# DO NOT EDIT BY HAND
#' @include send.R
NULL

#' Send the command Input.dispatchKeyEvent
#' 
#' Dispatches a key event to the page.
#' 
#' @param promise An aynchronous result object.
#' @param type A character string. 
#'        Type of the key event. Accepted values: keyDown, keyUp, rawKeyDown, char.
#' @param modifiers Optional. An integer. 
#'        Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8
#'        (default: 0). 
#' @param timestamp Optional. A TimeSinceEpoch. 
#'        Time at which the event occurred. 
#' @param text Optional. A character string. 
#'        Text as generated by processing a virtual key code with a keyboard layout. Not needed for
#'        for `keyUp` and `rawKeyDown` events (default: "") 
#' @param unmodifiedText Optional. A character string. 
#'        Text that would have been generated by the keyboard if no modifiers were pressed (except for
#'        shift). Useful for shortcut (accelerator) key handling (default: ""). 
#' @param keyIdentifier Optional. A character string. 
#'        Unique key identifier (e.g., 'U+0041') (default: ""). 
#' @param code Optional. A character string. 
#'        Unique DOM defined string value for each physical key (e.g., 'KeyA') (default: ""). 
#' @param key Optional. A character string. 
#'        Unique DOM defined string value describing the meaning of the key in the context of active
#'        modifiers, keyboard layout, etc (e.g., 'AltGr') (default: ""). 
#' @param windowsVirtualKeyCode Optional. An integer. 
#'        Windows virtual key code (default: 0). 
#' @param nativeVirtualKeyCode Optional. An integer. 
#'        Native virtual key code (default: 0). 
#' @param autoRepeat Optional. A logical. 
#'        Whether the event was generated from auto repeat (default: false). 
#' @param isKeypad Optional. A logical. 
#'        Whether the event was generated from the keypad (default: false). 
#' @param isSystemKey Optional. A logical. 
#'        Whether the event was a system key event (default: false). 
#' @param location Optional. An integer. 
#'        Whether the event was from the left or right side of the keyboard. 1=Left, 2=Right (default:
#'        0). 
#' 
#' @return A promise (following the definition of the promises package).
#'         The value of the fulfilled promise is a named list of length 0.
#' @export
Input.dispatchKeyEvent <- function(promise, type, modifiers = NULL, timestamp = NULL, text = NULL, unmodifiedText = NULL, keyIdentifier = NULL, code = NULL, key = NULL, windowsVirtualKeyCode = NULL, nativeVirtualKeyCode = NULL, autoRepeat = NULL, isKeypad = NULL, isSystemKey = NULL, location = NULL) {
  method <- 'Input.dispatchKeyEvent'
  args <- rlang::fn_fmls_names()
  args <- args[!sapply(mget(args), is.null)]
  params <- mget(args)
  names(params) <- args
  params <- if (length(params) > 1) params[2:length(params)] else NULL
  send(promise, method, params)
}


#' Send the command Input.insertText
#' 
#' This method emulates inserting text that doesn't come from a key press,
#'        for example an emoji keyboard or an IME.
#' 
#' @param promise An aynchronous result object.
#' @param text A character string. 
#'        The text to insert. 
#' 
#' @return A promise (following the definition of the promises package).
#'         The value of the fulfilled promise is a named list of length 0.
#' @export
Input.insertText <- function(promise, text) {
  method <- 'Input.insertText'
  args <- rlang::fn_fmls_names()
  args <- args[!sapply(mget(args), is.null)]
  params <- mget(args)
  names(params) <- args
  params <- if (length(params) > 1) params[2:length(params)] else NULL
  send(promise, method, params)
}


#' Send the command Input.dispatchMouseEvent
#' 
#' Dispatches a mouse event to the page.
#' 
#' @param promise An aynchronous result object.
#' @param type A character string. 
#'        Type of the mouse event. Accepted values: mousePressed, mouseReleased, mouseMoved, mouseWheel.
#' @param x A numeric. 
#'        X coordinate of the event relative to the main frame's viewport in CSS pixels. 
#' @param y A numeric. 
#'        Y coordinate of the event relative to the main frame's viewport in CSS pixels. 0 refers to
#'        the top of the viewport and Y increases as it proceeds towards the bottom of the viewport. 
#' @param modifiers Optional. An integer. 
#'        Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8
#'        (default: 0). 
#' @param timestamp Optional. A TimeSinceEpoch. 
#'        Time at which the event occurred. 
#' @param button Optional. A character string. 
#'        Mouse button (default: "none"). Accepted values: none, left, middle, right.
#' @param clickCount Optional. An integer. 
#'        Number of times the mouse button was clicked (default: 0). 
#' @param deltaX Optional. A numeric. 
#'        X delta in CSS pixels for mouse wheel event (default: 0). 
#' @param deltaY Optional. A numeric. 
#'        Y delta in CSS pixels for mouse wheel event (default: 0). 
#' 
#' @return A promise (following the definition of the promises package).
#'         The value of the fulfilled promise is a named list of length 0.
#' @export
Input.dispatchMouseEvent <- function(promise, type, x, y, modifiers = NULL, timestamp = NULL, button = NULL, clickCount = NULL, deltaX = NULL, deltaY = NULL) {
  method <- 'Input.dispatchMouseEvent'
  args <- rlang::fn_fmls_names()
  args <- args[!sapply(mget(args), is.null)]
  params <- mget(args)
  names(params) <- args
  params <- if (length(params) > 1) params[2:length(params)] else NULL
  send(promise, method, params)
}


#' Send the command Input.dispatchTouchEvent
#' 
#' Dispatches a touch event to the page.
#' 
#' @param promise An aynchronous result object.
#' @param type A character string. 
#'        Type of the touch event. TouchEnd and TouchCancel must not contain any touch points, while
#'        TouchStart and TouchMove must contains at least one. Accepted values: touchStart, touchEnd, touchMove, touchCancel.
#' @param touchPoints A list of TouchPoint. 
#'        Active touch points on the touch device. One event per any changed point (compared to
#'        previous touch event in a sequence) is generated, emulating pressing/moving/releasing points
#'        one by one. 
#' @param modifiers Optional. An integer. 
#'        Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8
#'        (default: 0). 
#' @param timestamp Optional. A TimeSinceEpoch. 
#'        Time at which the event occurred. 
#' 
#' @return A promise (following the definition of the promises package).
#'         The value of the fulfilled promise is a named list of length 0.
#' @export
Input.dispatchTouchEvent <- function(promise, type, touchPoints, modifiers = NULL, timestamp = NULL) {
  method <- 'Input.dispatchTouchEvent'
  args <- rlang::fn_fmls_names()
  args <- args[!sapply(mget(args), is.null)]
  params <- mget(args)
  names(params) <- args
  params <- if (length(params) > 1) params[2:length(params)] else NULL
  send(promise, method, params)
}


#' Send the command Input.emulateTouchFromMouseEvent
#' 
#' Emulates touch event from the mouse event parameters.
#' 
#' @param promise An aynchronous result object.
#' @param type A character string. 
#'        Type of the mouse event. Accepted values: mousePressed, mouseReleased, mouseMoved, mouseWheel.
#' @param x An integer. 
#'        X coordinate of the mouse pointer in DIP. 
#' @param y An integer. 
#'        Y coordinate of the mouse pointer in DIP. 
#' @param button A character string. 
#'        Mouse button. Accepted values: none, left, middle, right.
#' @param timestamp Optional. A TimeSinceEpoch. 
#'        Time at which the event occurred (default: current time). 
#' @param deltaX Optional. A numeric. 
#'        X delta in DIP for mouse wheel event (default: 0). 
#' @param deltaY Optional. A numeric. 
#'        Y delta in DIP for mouse wheel event (default: 0). 
#' @param modifiers Optional. An integer. 
#'        Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8
#'        (default: 0). 
#' @param clickCount Optional. An integer. 
#'        Number of times the mouse button was clicked (default: 0). 
#' 
#' @return A promise (following the definition of the promises package).
#'         The value of the fulfilled promise is a named list of length 0.
#' @export
Input.emulateTouchFromMouseEvent <- function(promise, type, x, y, button, timestamp = NULL, deltaX = NULL, deltaY = NULL, modifiers = NULL, clickCount = NULL) {
  method <- 'Input.emulateTouchFromMouseEvent'
  args <- rlang::fn_fmls_names()
  args <- args[!sapply(mget(args), is.null)]
  params <- mget(args)
  names(params) <- args
  params <- if (length(params) > 1) params[2:length(params)] else NULL
  send(promise, method, params)
}


#' Send the command Input.setIgnoreInputEvents
#' 
#' Ignores input events (useful while auditing page).
#' 
#' @param promise An aynchronous result object.
#' @param ignore A logical. 
#'        Ignores input events processing when set to true. 
#' 
#' @return A promise (following the definition of the promises package).
#'         The value of the fulfilled promise is a named list of length 0.
#' @export
Input.setIgnoreInputEvents <- function(promise, ignore) {
  method <- 'Input.setIgnoreInputEvents'
  args <- rlang::fn_fmls_names()
  args <- args[!sapply(mget(args), is.null)]
  params <- mget(args)
  names(params) <- args
  params <- if (length(params) > 1) params[2:length(params)] else NULL
  send(promise, method, params)
}


#' Send the command Input.synthesizePinchGesture
#' 
#' Synthesizes a pinch gesture over a time period by issuing appropriate touch events.
#' 
#' @param promise An aynchronous result object.
#' @param x A numeric. 
#'        X coordinate of the start of the gesture in CSS pixels. 
#' @param y A numeric. 
#'        Y coordinate of the start of the gesture in CSS pixels. 
#' @param scaleFactor A numeric. 
#'        Relative scale factor after zooming (>1.0 zooms in, <1.0 zooms out). 
#' @param relativeSpeed Optional. An integer. 
#'        Relative pointer speed in pixels per second (default: 800). 
#' @param gestureSourceType Optional. A GestureSourceType. 
#'        Which type of input events to be generated (default: 'default', which queries the platform
#'        for the preferred input type). 
#' 
#' @return A promise (following the definition of the promises package).
#'         The value of the fulfilled promise is a named list of length 0.
#' @export
Input.synthesizePinchGesture <- function(promise, x, y, scaleFactor, relativeSpeed = NULL, gestureSourceType = NULL) {
  method <- 'Input.synthesizePinchGesture'
  args <- rlang::fn_fmls_names()
  args <- args[!sapply(mget(args), is.null)]
  params <- mget(args)
  names(params) <- args
  params <- if (length(params) > 1) params[2:length(params)] else NULL
  send(promise, method, params)
}


#' Send the command Input.synthesizeScrollGesture
#' 
#' Synthesizes a scroll gesture over a time period by issuing appropriate touch events.
#' 
#' @param promise An aynchronous result object.
#' @param x A numeric. 
#'        X coordinate of the start of the gesture in CSS pixels. 
#' @param y A numeric. 
#'        Y coordinate of the start of the gesture in CSS pixels. 
#' @param xDistance Optional. A numeric. 
#'        The distance to scroll along the X axis (positive to scroll left). 
#' @param yDistance Optional. A numeric. 
#'        The distance to scroll along the Y axis (positive to scroll up). 
#' @param xOverscroll Optional. A numeric. 
#'        The number of additional pixels to scroll back along the X axis, in addition to the given
#'        distance. 
#' @param yOverscroll Optional. A numeric. 
#'        The number of additional pixels to scroll back along the Y axis, in addition to the given
#'        distance. 
#' @param preventFling Optional. A logical. 
#'        Prevent fling (default: true). 
#' @param speed Optional. An integer. 
#'        Swipe speed in pixels per second (default: 800). 
#' @param gestureSourceType Optional. A GestureSourceType. 
#'        Which type of input events to be generated (default: 'default', which queries the platform
#'        for the preferred input type). 
#' @param repeatCount Optional. An integer. 
#'        The number of times to repeat the gesture (default: 0). 
#' @param repeatDelayMs Optional. An integer. 
#'        The number of milliseconds delay between each repeat. (default: 250). 
#' @param interactionMarkerName Optional. A character string. 
#'        The name of the interaction markers to generate, if not empty (default: ""). 
#' 
#' @return A promise (following the definition of the promises package).
#'         The value of the fulfilled promise is a named list of length 0.
#' @export
Input.synthesizeScrollGesture <- function(promise, x, y, xDistance = NULL, yDistance = NULL, xOverscroll = NULL, yOverscroll = NULL, preventFling = NULL, speed = NULL, gestureSourceType = NULL, repeatCount = NULL, repeatDelayMs = NULL, interactionMarkerName = NULL) {
  method <- 'Input.synthesizeScrollGesture'
  args <- rlang::fn_fmls_names()
  args <- args[!sapply(mget(args), is.null)]
  params <- mget(args)
  names(params) <- args
  params <- if (length(params) > 1) params[2:length(params)] else NULL
  send(promise, method, params)
}


#' Send the command Input.synthesizeTapGesture
#' 
#' Synthesizes a tap gesture over a time period by issuing appropriate touch events.
#' 
#' @param promise An aynchronous result object.
#' @param x A numeric. 
#'        X coordinate of the start of the gesture in CSS pixels. 
#' @param y A numeric. 
#'        Y coordinate of the start of the gesture in CSS pixels. 
#' @param duration Optional. An integer. 
#'        Duration between touchdown and touchup events in ms (default: 50). 
#' @param tapCount Optional. An integer. 
#'        Number of times to perform the tap (e.g. 2 for double tap, default: 1). 
#' @param gestureSourceType Optional. A GestureSourceType. 
#'        Which type of input events to be generated (default: 'default', which queries the platform
#'        for the preferred input type). 
#' 
#' @return A promise (following the definition of the promises package).
#'         The value of the fulfilled promise is a named list of length 0.
#' @export
Input.synthesizeTapGesture <- function(promise, x, y, duration = NULL, tapCount = NULL, gestureSourceType = NULL) {
  method <- 'Input.synthesizeTapGesture'
  args <- rlang::fn_fmls_names()
  args <- args[!sapply(mget(args), is.null)]
  params <- mget(args)
  names(params) <- args
  params <- if (length(params) > 1) params[2:length(params)] else NULL
  send(promise, method, params)
}
